ebi-gene-expression-group/atlas-components

packages/eslint-config/index.js, packages/eslint-config/package-lock.json, packages/eslint-config/package.json
Use [babel-eslint](https://github.com/babel/babel-eslint) instead of [eslint](https://eslint.org/) to support later ES features (e.g. v2.0.0 of the experiments table uses class properties).
=> 📦 eslint-config 💬 Support more recent ES syntax

packages/atlas-experiment-table/__test__/TableFooter.test.js, packages/atlas-experiment-table/src/TableFooter.js, packages/atlas-experiment-table/src/TableManager.js
We need to handle the case of all rows shown (`rowsPerPage` is 0) as a special one, we can’t rely on the logic of `jw-paginate`.
=> 📦 atlas-experiment-table 💬 Bugfix #171767237 – Table footer shows `Infinity` in total number of pages if all rows are displayed

packages/scxa-tsne-plot/html/index.html, packages/scxa-tsne-plot/src/ClusterTSnePlot.js, packages/scxa-tsne-plot/src/plotloader/ScatterPlot.js
- Fixed the clipping of tooltips with the new `tooltip.outside: true` field
- Remove spacing around the chart to show the Y axis and have everything be a bit tighter
- Increase size of dot size in big datasets
- Correctly add `boost` module (it was working alright but...)
- Disable dimming of other series when hovering
=> 📦 scxa-tsne-plot 💬 Feature #171899505 – Visual improvements for the t-SNE plot

packages/scxa-gene-search-form/__test__/Autocomplete.test.js, packages/scxa-gene-search-form/__test__/__snapshots__/Autocomplete.test.js.snap, packages/scxa-gene-search-form/__test__/__snapshots__/GeneSearchForm.test.js.snap, packages/scxa-gene-search-form/__test__/__snapshots__/LabelledSelect.test.js.snap, packages/scxa-gene-search-form/package-lock.json, packages/scxa-gene-search-form/package.json, packages/scxa-gene-search-form/src/Autocomplete.js, packages/scxa-gene-search-form/src/FetchLoader.js, packages/scxa-gene-search-form/src/GeneSearchForm.js, packages/scxa-gene-search-form/src/index.js
For Cambridge Cell Atlas, having a text label on top of the text input doesn’t look very good:
So I added a prop so that we can hide it.
=> 📦 scxa-gene-search-form 💬 Feature #171953862 – Add gene search form to CCA

packages/atlas-experiment-table/__test__/TableManager.test.js, packages/atlas-experiment-table/__test__/search.test.js, packages/atlas-experiment-table/src/TableManager.js, packages/atlas-experiment-table/src/search.js
The way to fix this issue was to broaden the default search results so that it matches any of the typed words in any order. In this way *Canis familiaris* matches *Canis lupus familiaris*, and also *familiaris canis* or *canis foobar* would. I decided to add an exact search if the searched phrase is enclosed in double quotes after running a poll in our Slack workspace.
=> 📦 atlas-experiment-table 💬 Bugfix #172189793 – Canis familiaris can’t find Canis lupus familiaris

packages/scxa-tsne-plot/html/Demo.js, packages/scxa-tsne-plot/src/plotloader/ScatterPlot.js
Bug: When user try to download large experiments in the single-cell atlas, high charts export server giving error `
> 413 Request Entity Too Large
As per @alfonsomunozpomer  - added 'offline-exporting' module and wrap that in the high charts module which we are already doing. 
I have followed this [JSFiddle](https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/highcharts/exporting/offline-download-demo/) to fix this
=> Scxa tsne plot/bugfix/172954811 export as image fails

packages/scxa-tsne-plot/__test__/ClusterTSnePlot.test.js, packages/scxa-tsne-plot/html/Demo.js, packages/scxa-tsne-plot/package-lock.json, packages/scxa-tsne-plot/package.json, packages/scxa-tsne-plot/src/ClusterTSnePlot.js, packages/scxa-tsne-widget/package-lock.json, packages/scxa-tsne-widget/package.json
Adding both an single colour point and also a series colour (seemingly) made Not Available points invisible. It’s either an undefined behaviour in Highcharts or the opacity was reduced twice (set to 0.65 × 0.65). With the added inconvenience that it wasn’t consistent, so I suspect it’s the former.
=> 📦 scxa-tsne-plot 💬 Bugfix #174357060 – Not Available points not visible

packages/scxa-tsne-plot/package-lock.json, packages/scxa-tsne-plot/package.json, packages/scxa-tsne-plot/src/plotloader/modules/coloraxis-logarithmic-with-negative-values.js, packages/scxa-tsne-widget/package-lock.json, packages/scxa-tsne-widget/package.json
**Very annoyingly**, this doesn’t manifest in the `scxa-tsne-plot` package, only when it’s integrated in the experiment page. Very probably, something to do with how rendering and initialising the Highcharts object is handled. The fact that [the updated negative log fiddle](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/coloraxis/logarithmic-with-emulate-negative-values/) changes the first event from `init` to `afterInit` reinforces my suspicion.
=> 📦 scxa-tsne-plot 💬 Bugfix #174786132 – 0 expression values breaks the plot when integrated in the experiment page

packages/scxa-tsne-plot/__test__/ClusterTSnePlot.test.js, packages/scxa-tsne-plot/html/Demo.js, packages/scxa-tsne-plot/src/ClusterTSnePlot.js, packages/scxa-tsne-plot/src/TSnePlotView.js
I have added additional props in `TSnePlotView.js` to be a bit flexible in the sense if in future the values change so we can pass them as props from `jsp` rather than hardcoding. I have also added a test case to see if `inferred_cell_type` is selected by default if it exists. The details of the story are [here](https://www.pivotaltracker.com/story/show/174292400).
=> Select inferred cell type by default to color by if they exist

packages/scxa-tsne-plot/__test__/ClusterTSnePlot.test.js, packages/scxa-tsne-plot/__test__/__snapshots__/ClusterTSnePlot.test.js.snap, packages/scxa-tsne-plot/html/Demo.js, packages/scxa-tsne-plot/src/ClusterTSnePlot.js, packages/scxa-tsne-plot/src/TSnePlotView.js
The task is related to this [pivotal story](https://www.pivotaltracker.com/story/show/177160800). For this task I'm using the approach where the details regarding these two new dropdowns will be passed as props in the following data structure:
> plotTypeDropdown: [
{
plotType: `TSne`,
plotOptionsLabel: `Perplexities`,
plotOptions: [1, 2, 3, 4]
},
{
plotType: `UMap`,
plotOptionsLabel: `N-neighbors`,
plotOptions: [1, 2, 3]
}
]
The new prop name is `plotTypeDropdown` which is an array of objects each of which contains:
- Type of the plot
- Label to display over dropdown
- And the options to be displayed in the dropdown
The flexibility of such a data structure allows us to add more types of dropdowns in the future without changing any front-end code .
=> Divide perplexity dropdown to two dropdowns

packages/atlas-experiment-table/__test__/TableManager.test.js, packages/atlas-experiment-table/src/TableManager.js
We had an issue while integrating Anatomograms and Experiment Table when a prop change was triggered by Anatomogram filtering. The prop change did not re-render the experiment table as there was no state change in the component. To fix this issue, I have implemented the componentDidUpdate function of React component lifecycle.
=> Re-render the component based on prop change

packages/scxa-tsne-plot/src/TSnePlotView.js
Add new endpoints for the (t-SNE/UMAP) cell plots:
` json/cell-plots/{experimentAccession}/clusters/k/{k}`
` json/cell-plots/{experimentAccession}/clusters/metadata/{metadataCategory}`
The plot type and options are all passed via request parameters:
` ?plotMethod=umap&n_neighbors=50`
` ?plotMethod=tsne&perplexity=30`
=> Change the tsne json endpoints for k and metadata

packages/atlas-react-fetch-loader/README.md, packages/atlas-react-fetch-loader/__test__/FetchLoader.test.js, packages/atlas-react-fetch-loader/package.json, packages/atlas-react-fetch-loader/src/FetchLoader.js
Add optional raw prop to unpack the response as text (defaults to `false`). We want this so that we can combine it with the [latest iteration of the information banner](https://github.com/ebi-gene-expression-group/atlas-components/pull/101) and fetch a Markdown file from a URL and display it.
=> 📦 Atlas React Fetch Loader – 💬 Add ability to fetch raw text

packages/atlas-react-fetch-loader/README.md, packages/atlas-react-fetch-loader/__test__/FetchLoader.test.js, packages/atlas-react-fetch-loader/package.json, packages/atlas-react-fetch-loader/src/FetchLoader.js
Add a prop to support query parameters (e.g. `?foo=bar`) in requests. The prop is an object that [can be parsed by URI.js as-is](https://medialize.github.io/URI.js/docs.html#accessors-search).
=> :package: atlas-react-fetch-loader :speech_balloon: Feature #179948196 – Support query request parameters

packages/scxa-tsne-plot/__test__/ClusterTSnePlot.test.js, packages/scxa-tsne-plot/src/ClusterTSnePlot.js
Massive `Not available` points will block other categories like below:
I added a z-index for each data series and make sure `Not available` is a negative and solve the issue:
=> 📦 scxa-tsne-plot 💬 Feature #181139004 – Move back 'Not available' metadata categories

eslint-config/README.md, eslint-config/index.js, eslint-config/package.json
Add a rule that follows our coding style. You can see some examples at https://eslint.org/docs/latest/rules/space-before-function-paren#anonymous-always-named-never-asyncarrow-always.
=> 📦 eslint-config 💬 Adjust rules for spacing argument block in fucntion declarations

packages/scxa-cell-type-wheel/cypress/component/CellTypeWheel.cy.js, packages/scxa-cell-type-wheel/cypress/fixtures/cancer.json, packages/scxa-cell-type-wheel/src/CellTypeWheel.js
Cell type data labels are hidden while in a small window for example Homo Sapiens > brain. I fixed it by disabling the `rotationMode` and add a cypress test for it.
=> Fix cell type data label not showing & add a test

packages/scxa-faceted-search-results/html/fetch-loader/ExperimentCard.js, packages/scxa-faceted-search-results/html/fetch-loader/ExperimentsHeader.js
Gene search result card added a new column to experiment type icon to distinguish anndata and the others. A tooltip is added if users hover on the icon. This is not a src code implementation, so there is no new test for it. Our component is compatible with new header and card style.
=> Add a visual UI distinction for anndata experiments in the gene search results

packages/scxa-tsne-plot/html/Demo.js, packages/scxa-tsne-plot/src/TSnePlotView.js
We need to change these two methods:
- https://github.com/ebi-gene-expression-group/atlas-components/blob/9301396f596483e45946a16eb9c4cd7dd16e20af/packages/scxa-tsne-plot/src/TSnePlotView.js#L58
- https://github.com/ebi-gene-expression-group/atlas-components/blob/9301396f596483e45946a16eb9c4cd7dd16e20af/packages/scxa-tsne-plot/src/TSnePlotView.js#L80
Do not process the URL text outside of URI (e.g. https://github.com/ebi-gene-expression-group/atlas-components/blob/9301396f596483e45946a16eb9c4cd7dd16e20af/packages/scxa-tsne-plot/src/TSnePlotView.js#L67), you must use URI’s API to create the URL and the last method should always be .toString().
The endpoint for default plotTypes is provided in the PR https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/272. I am trying to …
=>  📦 scxa-tsne-plot 💬 feature: Use default plot method and parameterisation from backend props

packages/atlas-experiment-table/__test__/TableCell.test.js, packages/atlas-experiment-table/__test__/experiments-sc.json, packages/atlas-experiment-table/html/index-sc.html, packages/atlas-experiment-table/src/TableCell.js
We add an icon column for experiment table to mark if it is anndata or not. We don't have a proper endpoint for anndata experiment type yet, so I pick the frontend solution. A jest test is added for the new feature.
=> Add a visual UI distinction for anndata experiments in the experiments table

packages/scxa-tsne-plot/html/Demo.js, packages/scxa-tsne-plot/src/TSnePlotView.js
We need to fix two things here:
1. `tsne` and `umap` from cell plot endpoint changed to `t-SNE` and `UMAP`
2. the default parameter and method props from experiment page endpoint is `defaultPlotMethodAndParameterisation` 
TODO: 3. Make the dropdown options dynamiclly rather than hard coded values for `t-SNE` or `UMAP`
Reviewer may test this PR under the latest postgres database.
=> Fix tsne and umap format and default parameter

packages/atlas-experiment-table/__test__/TableCell.test.js, packages/atlas-experiment-table/__test__/head/__snapshots__/TableHeaderCell.test.js.snap, packages/atlas-experiment-table/html/index-sc.html, packages/atlas-experiment-table/package.json, packages/atlas-experiment-table/src/TableCell.js, packages/atlas-experiment-table/src/TableContent.js
We changed the requirement to add an Anndata icon to the experiment table title column in SC, rather than adding an image column like what we have in bulk experiment page. If the experiment is not an `E-ANND` type, then no icons should be shown as discussed with @Silvie.
We need to make the experiment table component compilable with bulk and SC pages.
Anndata icon image should be added into the backend `resource` as `differential` icons in bulk. For now, I am just using the source link `https://www.ebi.ac.uk/gxa/resources/images/experiments-table/differential.png` for anndata at this development stage. We will need to update this in the javascript bundle in `atlas-web-single-cell` repository to integrit this change to SC application.
FYI: A test Anndata experiment is in page 13 as shown …
=> Atlas experiment table/add anndata to exp title column

packages/atlas-anatomogram-experiment-table/package-lock.json, packages/atlas-anatomogram-experiment-table/package.json, packages/atlas-experiment-table/package-lock.json, packages/atlas-experiment-table/package.json, packages/atlas-experiment-table/src/TableCell.js, packages/scxa-faceted-search-results/html/fetch-loader/ExperimentCard.js, packages/scxa-faceted-search-results/package-lock.json, packages/scxa-faceted-search-results/package.json
Icon changed from `A` to  `E`, and the tooltip text is  `Externally analysed data`.
=> 418 updata anndata icon and title on scxa gene search and experiment table pages

packages/scxa-cell-type-wheel-experiment-heatmap/cypress/component/CellTypeWheelExperimentHeatmap.cy.js, packages/scxa-cell-type-wheel-experiment-heatmap/package.json, packages/scxa-cell-type-wheel-experiment-heatmap/src/CellTypeWheelExperimentHeatmap.js, packages/scxa-gene-search-form/package.json, packages/scxa-gene-search-form/src/GeneSearchForm.js
Species parameter was ignored when it was provided as a URL request parameter.
With this change I set the species parameter on the `GeneSearchForm` and also pass it to the `CellTypeWheelFetchLoader`.
I also added 3 new test cases to cover these cases.
=> [bugfix] Set provided species parameter to GeneSearchForm

packages/scxa-cell-type-wheel-experiment-heatmap/src/CellTypeWheelExperimentHeatmap.js, packages/scxa-cell-type-wheel/html/data/mus-musculus.json, packages/scxa-cell-type-wheel/html/index.html, packages/scxa-cell-type-wheel/html/mus-musculus.html, packages/scxa-cell-type-wheel/html/render.js, packages/scxa-cell-type-wheel/src/CellTypeWheel.js
In `scxa-cell-type-wheel` component, we hard-coded to make a gene heatmap search at node level 4, that's right for cell type metadata search, rather than for `species` metadata search. We need to make a condition to check if the search term is `species` or not by fetching all possible species from the `scxa-cell-type-wheel-experiment-heatmap` component.
If you want to test it locally, please remember to build a local `scxa-cell-type-wheel` package by typing `npm pack` under its directory and install with the absolute/relative directory in `scxa-cell-type-wheel-experiment-heatmap` component.
I also created a html demo page for `Mus muscuslus` search term in `scxa-cell-type-wheel` component, with altered json response, by removing the incorrect entry with `Homo sapiens`. This entry issue …
=> Species search cell type wheel not clickable

packages/atlas-anatomogram-experiment-table/package-lock.json, packages/atlas-anatomogram-experiment-table/package.json, packages/atlas-experiment-table/package-lock.json, packages/atlas-experiment-table/package.json, packages/scxa-cell-type-wheel-experiment-heatmap/package-lock.json, packages/scxa-cell-type-wheel-experiment-heatmap/package.json, packages/scxa-cell-type-wheel/package-lock.json, packages/scxa-cell-type-wheel/package.json, packages/scxa-faceted-search-results/package-lock.json, packages/scxa-faceted-search-results/package.json, packages/scxa-gene-search-form/package-lock.json, packages/scxa-gene-search-form/package.json, packages/scxa-tsne-plot/__test__/ClusterTSnePlot.test.js, packages/scxa-tsne-plot/html/Demo.js, packages/scxa-tsne-plot/package-lock.json, packages/scxa-tsne-plot/package.json, packages/scxa-tsne-plot/src/ClusterTSnePlot.js, packages/scxa-tsne-widget/package-lock.json, packages/scxa-tsne-widget/package.json
In this example experiment page, https://www-test.ebi.ac.uk/gxa/sc/experiments/E-ANND-3/results/, `ks` is empty, i.e. `ks=[]` in the page content, so we need to make a new feature in the tsne plot, to handle this case.
=> Cell plots ks are not always required for anndata experiments

packages/atlas-experiment-table/html/index-sc.html, packages/atlas-experiment-table/src/TableCell.js
Given the commits to help page repo by Silvie, and the backend PR https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/459  implemented, the link is `http://localhost:8080/gxa/sc/help.html?section=external-data` .
We may need to publish a new package version for atlas-experiment-table component and integrate into the backend PR.
=> Add external data help page hyperlink

packages/scxa-marker-gene-heatmap/package.json, packages/scxa-marker-gene-heatmap/src/MarkerGeneHeatmap.js
We had some UI issues in cell-type marker gene heatmap, while the cell type name is too long, and it will be overlapped with each other and users may not read it properly.
Given the discussion in the team meeting, we agreed that to make the cell type name at the right side column, tilted a bit like the title at the top row, and if it's still too long, we need to use `...` to shorten it.
Regarding the tests, actually, we just need to update the snapshots but we do not have any test configuration yet, this issue will be fixed in my another PR https://github.com/ebi-gene-expression-group/atlas-components/pull/178. I will suggest we do not worry the tests for this PR yet, and  we can upate the snapshots in the test refactoring PR instead.
=> 173 overlapping names in the marker gene heat map

packages/scxa-cell-type-wheel-experiment-heatmap/cypress/component/CellTypeWheelExperimentHeatmap.cy.js, packages/scxa-cell-type-wheel-experiment-heatmap/package-lock.json, packages/scxa-cell-type-wheel-experiment-heatmap/package.json, packages/scxa-cell-type-wheel-experiment-heatmap/src/CellTypeWheelExperimentHeatmap.js
Fix for the front end(web app) and backend endpoint (API) to accept / in the cell type 
Endpoint `- /json/cell-type-marker-genes/{cellType}`
=> scxa-cell-type-wheel-experiment-heatmap/bugfix/encode-slash-for-cell-type

packages/scxa-marker-gene-heatmap/__test__/CalloutAlert.test.js, packages/scxa-marker-gene-heatmap/__test__/CellTypeMarkerGeneHeatmap.test.js, packages/scxa-marker-gene-heatmap/__test__/HeatmapView.test.js, packages/scxa-marker-gene-heatmap/__test__/LoadingOverlay.test.js, packages/scxa-marker-gene-heatmap/__test__/__snapshots__/HeatmapView.test.js.snap, packages/scxa-marker-gene-heatmap/__test__/__snapshots__/LoadingOverlay.test.js.snap, packages/scxa-marker-gene-heatmap/package.json
We used `enzyme` before to test marker-gene-heatmap component, which is based on React 16, and since we updated the react into 17, the tests had been suspended, in another word, we do not have any tests for this component currently.
To make a running jest tests again, I found out that `@testing-library/react` is very convinient and well-documented and keep updated to React. Hence, I refactor this component with TLR.
=> 177 chore refactor scxa marker geneheatmap enzyme tests with react 17

packages/scxa-experiment-page/src/ExperimentPageSubTabRoute.js
Gene expression heatmap has a wrong initialization heatmap type. https://www-test.ebi.ac.uk/gxa/sc/experiments/E-MTAB-10448/results/marker-genes
This will happend to experiments do not have metadatas. Check the related issue for more information.
=> Fix the initialization issue on selected colour by category

packages/scxa-marker-gene-heatmap/__test__/CellTypeMarkerGeneHeatmap.test.js, packages/scxa-marker-gene-heatmap/__test__/MarkerGeneHeatmap.test.js, packages/scxa-marker-gene-heatmap/__test__/__snapshots__/MarkerGeneHeatmap.test.js.snap, packages/scxa-marker-gene-heatmap/__test__/heatmapOptionsProvider.test.js, packages/scxa-marker-gene-heatmap/src/HeatmapView.js, packages/scxa-marker-gene-heatmap/src/MarkerGeneHeatmap.js, packages/scxa-marker-gene-heatmap/src/splitPhrase.js, packages/scxa-marker-gene-heatmap/src/tooltip.js
As discribed in the related issue, we need to improve the right column labels for cell type marker gene heatmap.
=> Improve marker gene right column label UI

packages/scxa-tsne-plot/src/ClusterTSnePlot.js, packages/scxa-tsne-plot/src/GeneExpressionTSnePlot.js
Due to the `highcharts` package version update, the cell plots tooltip is not working well for large dataset. It's not from the refactoring json format, but the recent highcharts updates. Once it is over 50K, highcharts would drop unnecessary (while he thinks) fields from series data to provide better performance.
=> Bugfix cell plots tooltip cell id undefined
